### ISSUE TITLE
glTF 2.0 or 1.0

### ISSUE THREAD

**Issue by screwt** [Ybalrid/Ogre_glTF#6]
Hi,

Nice job done on your repot!
Could you tell me, does this project allows glTF 2.0 scene loading or only glTF 1.0?

Thanks in advance.

#-- edit after having a look to https://github.com/syoyo/tinygltf
i suppose it's glTF 2.0 compatible.

**Comment by Ybalrid** [comment]
This is glTF 2.0 yes. I should make thisclearer

**Comment by Ybalrid** [comment]
>  Could you tell me, does this project allows glTF 2.0 **scene** loading or only glTF 1.0?

@screwt Oh, also, as it is right now it's not actually loading "scenes", it's merely loading the first mesh it can find on the file. 

Scene loading will be added down the road, right now this library is far from being done and being "usable". But if you want to try it out, I'll appreciate any feedback! ;-)
