### ISSUE TITLE
Skeleton root bone child issue.

### ISSUE THREAD

**Issue by stig-atle** [Ybalrid/Ogre_glTF#8]
I tested a bit tonight with exported cylinder with bones.
It seems as if the gltf file has the mesh as a child to the root bone, so when the loader loads the file it tries to make the mesh as a bone - and fails.
So this means the root bones has two children, mesh and the next bone.

The test scene I used was the sample file that comes with the gltf blender addon.
[03_skinned_cylinder.blend](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scenes/03_skinned_cylinder.blend)

I added some more logging where the children are created, then I printed the name of the child.
You will then see the cylinder appear as the first child like this:
```
22:25:06: Bone 0 has 2 children
22:25:06: Looping through current child: Cylinder
```
(Cylinder is the name of the mesh object itself.).

**Comment by Ybalrid** [comment]
I'm going to install the Blender addon and export that object and see what's going on.
(you can also give me the exact gltf/glb file that was exported on your side here; just in case :wink: )

**Comment by stig-atle** [comment]
[from_gltf_export_skinned_cylinder.zip](https://github.com/Ybalrid/Ogre_glTF/files/2131184/from_gltf_export_skinned_cylinder.zip)

**Comment by Ybalrid** [comment]
Going to step through the skeleton reading with a debugger and look at the raw data in the json, see if nothing stupid is going on

**Comment by Ybalrid** [comment]
Indeed, the "root" node used here is 2, while the list of joints are the nodes 3 to 6 in the gltf hierarchy

**Comment by Ybalrid** [comment]
Okay, I think I found the "bug". The sample object that I was using while testing is using the same node index for it's "skeleton" object as for the first joint in it's array of joints. This seems that it's generally *not* the case.

As far as I can tell, the root bone is the first joint inside the skin object. After that, each of them define their list of children, so we can recurse through that...

**Comment by Ybalrid** [comment]
@stig-atle Can you confirm you don't have the original issue anymore with the latests commits on `master`?

**Comment by stig-atle** [comment]
It does not crash - all though I cannot see the geometry in the viewport either. I have to test some more to be sure things are in order.

**Comment by Ybalrid** [comment]
I actually haven't checked for the geometry. It may be just a matter of moving the camera inside the `main` in the test program, or changing the position/scale of the scene node

**Comment by Ybalrid** [comment]
The issue is a bit more complex that I thought originally, I'm trying to understand what exactly should be the transform to apply to the root bone/all the bones based on theses discussions and standard texts

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#joint-hierarchy

This whole twitter thread with Crashy https://twitter.com/LMCrashy/status/1015632363907403781

This issue with on the GLTF repository https://github.com/KhronosGroup/glTF/issues/1270

**Comment by Ybalrid** [comment]
@stig-atle Can you check with current master branch? Lots of fixes with the bone parsing were implemented. Including some bone indices that where messed-up

**Comment by Ybalrid** [comment]
I consider this fixed.
